server:
  port: 9257

swagger:
  enable: true
#  application-name: ${spring.application.name}
#  application-version: 1.0
#  application-description: 门禁后台接口
#  try-host: http://localhost:${server.port}

mybatis-plus:
  type-aliases-package: com.wim.aero.acs.db.**.entity
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

spring:
  profiles:
    active: "@profiles.active@"
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://113.57.214.58:14339;databaseName=ykt?allowMultiQueries=true
    username: sa
    password: iafc@2022
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 900000
      filters: stat,wall,slf4j,commonlogging
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        #是否启用StatFilter默认值false
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: Iafc
        allow:
        # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
        # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
        aop-patterns: com.wim.acs.*.service.*
      filter:
        wall:
          config:
            none-base-statement-allow: true
            multi-statement-allow: true
        commons-log:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: false

  activemq:
#    in-memory: true
    broker-url: tcp://192.168.2.236:61616
    user: admin
    password: zhdt@2022
#    packages:
#      trust-all: true
    pool:
      enabled: true
      max-connections: 20
      idle-timeout: 30000
    #队列名称
    queueName:
      # 访问事件队列
      accessQueue: accessQueue
      # 告警事件队列
      alarmQueue: alarmQueue
      #日志事件队列
      logQueue: logQueue
      #设备状态队列
      statusQueue: statusQueue
      #控制器消息队列
      scpSeqQueue: scpSeqQueue
      #控制器MAC消息队列
      scpMacQueue: scpMacQueue

  jms:
    listener:
      concurrency: 10
      max-concurrency: 20

#  redis:
#    # 地址
#    host: 47.97.215.180
#    # 端口，默认为6379
#    port: 6379
#    # 数据库索引
#    database: 0
#    # 密码
#    password: Iafc!aliyun777
#    timeout: 5000ms # 连接超时时间（毫秒）
#    lettuce:
#      pool:
#        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 10 # 连接池中的最大空闲连接
#        min-idle: 5 # 连接池中的最小空闲连接
#        max-wait: 5000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）


logging:
  level:
    root: INFO


httppool:
  maxTotal: 200
  defaultMaxPerRoute: 100
  connectTimeout: 3000
  connectionRequestTimeout: 3000
  socketTimeout: 3000
  validateAfterInactivity: 2000

comm-service-info:
  url: https://192.168.2.72:7087

dst:
  list:
    - start: "2022/03/13 02:00:00"
      end: "2022/11/06 01:00:00"
    - start: "2023/03/12 02:00:00"
      end: "2023/11/05 01:00:00"
    - start: "2024/03/10 02:00:00"
      end: "2024/11/03 01:00:00"
    - start: "2025/03/09 02:00:00"
      end: "2025/11/02 01:00:00"
    - start: "2026/03/08 02:00:00"
      end: "2026/11/01 01:00:00"
    - start: "2027/03/14 02:00:00"
      end: "2027/11/07 01:00:00"
    - start: "2028/03/12 02:00:00"
      end: "2028/11/05 01:00:00"
    - start: "2029/03/11 02:00:00"
      end: "2029/11/04 01:00:00"
    - start: "2030/03/10 02:00:00"
      end: "2030/11/03 01:00:00"
    - start: "2031/03/09 02:00:00"
      end: "2031/11/02 01:00:00"
    - start: "2032/03/14 02:00:00"
      end: "2032/11/07 01:00:00"
    - start: "2033/03/13 02:00:00"
      end: "2033/11/06 01:00:00"
    - start: "2034/03/12 02:00:00"
      end: "2034/11/05 01:00:00"
    - start: "2035/03/11 02:00:00"
      end: "2035/11/04 01:00:00"

aero-scp-sepcification:
  #rs485波特率
  rs485Baud: 38400
  #最大事件数量
  maxTransactions: 100000
  #最大访问级别数量
  maxAcessLevel: 32000
  #最多触发器数量
  maxTrigger: 100
  #最大过程调用(内部变量)
  maxProcedure: 100
  #最大时间区数量
  maxTimeZone: 255
  #最大假日数量
  maxHoliday: 255
  #最大为上传事件数量
  maxTranLimit: 100000
  #最大防区组数量
  maxMpg: 128
  #操作模式数量
  operModes: 1
  #操作类型
  operTypes: 0